[package]
name = "mpd_protocol"
version = "0.1.0"
authors = ["Ole Bertram <git@bertr.am>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { git = "https://github.com/tokio-rs/bytes" }
tokio-util = { git = "https://github.com/tokio-rs/tokio" }
nom = "5"
