[package]
name = "mpd_protocol"
version = "0.7.0"
authors = ["Ole Bertram <git@bertr.am>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "Implementation of MPD client protocol"
repository = "https://github.com/elomatreb/mpd_protocol"
readme = "README.md"
keywords = ["mpd", "protocol", "client"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.4"
tokio-util = { version = "0.3.1", features = ["codec"] }
nom = "5.1.1"
fnv = "1.0.6"
tracing = "0.1.13"
