[package]
name = "mpd_protocol"
version = "0.11.0"
authors = ["Ole Bertram <git@bertr.am>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Implementation of MPD client protocol"
repository = "https://github.com/elomatreb/mpd_protocol"
readme = "README.md"
keywords = ["mpd", "protocol", "client"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0.0"
tokio-util = { version = "0.6.0", features = ["codec"] }
tokio = { version = "1.0.1", features = ["io-util"] }
tracing = "0.1.21"
memchr = "2.3.4"
hashbrown = "0.11.2"

[dependencies.nom]
version = "6.0.0"
default-features = false
features = ["std"]

[dev-dependencies]
tokio = { version = "1.0.1", features = ["io-util", "rt", "macros"] }
tokio-test = "0.4.0"
futures = "0.3.6"
assert_matches = "1.5.0"
criterion = "0.3.4"

[[bench]]
name = "parse_response"
harness = false
