[package]
name = "mpd_protocol"
version = "0.8.1"
authors = ["Ole Bertram <git@bertr.am>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Implementation of MPD client protocol"
repository = "https://github.com/elomatreb/mpd_protocol"
readme = "README.md"
keywords = ["mpd", "protocol", "client"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.4"
tokio-util = { version = "0.3.1", features = ["codec"] }
tokio = { version = "0.2.22", features = ["io-util"] }
fxhash = "0.2.1"
tracing = "0.1.13"

[dependencies.nom]
version = "5.1.1"
default-features = false
features = ["std"]

[dev-dependencies]
tokio = { version = "0.2.22", features = ["io-util", "rt-core", "macros"] }
tokio-test = "0.2.1"
futures = "0.3.5"
