[package]
name = "mpd_protocol"
version = "0.1.0"
authors = ["Ole Bertram <git@bertr.am>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
tokio = "0.2.0-alpha.6"
regex = "1"
lazy_static = "1.4.0"
