[package]
name = "mpd_protocol"
version = "0.1.2"
authors = ["Ole Bertram <git@bertr.am>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "Implementation of MPD client protocol"
repository = "https://git.bertr.am/elomatreb/mpd_protocol"
readme = "README.md"
keywords = ["mpd", "protocol", "client"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5"
tokio-util = { version = "0.2", features = ["codec"] }
nom = "5"
log = "0.4"
